In [1]:
import pandas as pd
import os
import numpy as np
from datetime import datetime
from zoneinfo import ZoneInfo
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
pd.set_option('display.max_columns', None)

In [2]:
df_rep_errores= pd.read_excel('C:/DATOS/REPORTE ERRORES_3079_NUEVO.xlsx', sheet_name=0, dtype=str)
df_rep_errores.columns = (df_rep_errores.columns.str.strip().str.upper()
                            .str.replace(r'[^A-Za-z0-9]', '_', regex=True))
df_rep_errores.drop([''], axis=1, inplace=True)

In [3]:
df_rep_errores= df_rep_errores.rename(columns={'COD_DE_CERTIFICADO':'CODIGO_CERTIFICADO',
                                               'FEC__INICIO':'FECHA_INICIO', 'FEC__FIN':'FECHA_FIN',
                                                'PRIMABRUTACAN':'PRIMA_BRUTA', 'PRIMANETACAN':'PRIMA_NETA',
                                                'NOMCOMPLETO': 'NOMBRE_COMPLETO','APEPATERNO': 'APELLIDO_PATERNO',
                                                'APEMATERNO': 'APELLIDO_MATERNO','FECNACIMIENTO':'FECHA_NACIMIENTO',
                                                'TIPDOCUMENTO':'TIPO_DOCUMENTO','NUMDOCUMENTO':'NUM_DOCUMENTO'})

In [5]:
df_rep_errores['TIPO_MOVIMIENTO'] = df_rep_errores["TIPO_MOVIMIENTO"].str.upper()
df_rep_errores['ORIGEN_ERROR'] = df_rep_errores["ORIGEN_ERROR"].str.upper()
df_rep_errores['FECHA_CARGA']= pd.to_datetime(df_rep_errores['FECHA_CARGA'], errors='coerce').dt.date
df_rep_errores['FECHA_NACIMIENTO']= pd.to_datetime(df_rep_errores['FECHA_NACIMIENTO'], format='%Y%m%d', errors='coerce').dt.date
df_rep_errores['FECHA_INICIO']= pd.to_datetime(df_rep_errores['FECHA_INICIO'], format='%d/%m/%Y', errors='coerce').dt.date
df_rep_errores['FECHA_FIN']= pd.to_datetime(df_rep_errores['FECHA_FIN'], format='%d/%m/%Y', errors='coerce').dt.date
df_rep_errores['SUMA_ASEGURADA'] = pd.to_numeric(df_rep_errores['SUMA_ASEGURADA'], errors='coerce').astype('Float64')
df_rep_errores['TASA'] = pd.to_numeric(df_rep_errores['TASA'], errors='coerce').astype('Float64')
df_rep_errores['TASA_RECARGO'] = pd.to_numeric(df_rep_errores['TASA_RECARGO'], errors='coerce').astype('Float64')
df_rep_errores['PRIMA_BRUTA'] = pd.to_numeric(df_rep_errores['PRIMA_BRUTA'], errors='coerce').astype('Float64')
df_rep_errores['PRIMA_NETA'] = pd.to_numeric(df_rep_errores['PRIMA_NETA'], errors='coerce').astype('Float64')
df_rep_errores= df_rep_errores.fillna({'LINEA_TRAMA': 'SIN DATO'})

In [7]:
df_rep_errores.loc[df_rep_errores['MONEDA'].str.lower().isin(['sol','pen']), 'MONEDA'] = 'SOL'

In [8]:
df_rep_errores["CODIGO_SEGURO"] = np.where(df_rep_errores["LINEA_TRAMA"] != "SIN DATO",
                                            df_rep_errores["LINEA_TRAMA"].str[:3],'SIN DATO')
df_rep_errores["CODIGO_MOVIMIENTO"] = np.where(df_rep_errores["LINEA_TRAMA"] != "SIN DATO",
                                            df_rep_errores["LINEA_TRAMA"].str[48],'SIN DATO')

In [9]:
df_rep_errores['CODIGO_ERROR'] = df_rep_errores['CODIGO_ERROR'].apply(lambda x: str(x).zfill(4) if pd.notnull(x) else np.nan)

In [10]:
df_rep_errores['MONEDA'].value_counts()

MONEDA
SOL    159067
Name: count, dtype: int64

In [11]:
df_rep_errores[df_rep_errores['CODIGO_ERROR'].str.len() > 4].head()

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, CODIGO_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FECHA_INICIO, FECHA_FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMA_BRUTA, PRIMA_NETA, NOMBRE_COMPLETO, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR, DESCRIPCION_ERROR, CODIGO_SEGURO, CODIGO_MOVIMIENTO]
Index: []

In [12]:
df_rep_errores.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,CODIGO_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FECHA_INICIO,FECHA_FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMA_BRUTA,PRIMA_NETA,NOMBRE_COMPLETO,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,TIPO_DOCUMENTO,NUM_DOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR,CODIGO_SEGURO,CODIGO_MOVIMIENTO
0,122189,NaN,2018-01-09,3079,Desgravamen BANBIF TC,195480,Plan Tarjetas de Crédito (01-03-16),00009004400000012970,218560637,RENOVACION,2017-12-01,2018-01-01,SOL,3093.64,0.0,0.0,4.5,4.37,ANGELICA,OLANO,CIEZA,1978-10-14,2,16807045,20101036813_0137001_20171231_004.TXT,0000040506013740137001 33082482 ...,ERROR CANAL,7360,ERROR EN EL VALOR DEL CAMPO FECINIVIGENCIAPOLC...,000,
1,122189,NaN,2018-01-09,3079,Desgravamen BANBIF TC,195480,Plan Tarjetas de Crédito (01-03-16),00004067740000335797,218522726,RENOVACION,2017-12-01,2018-01-01,SOL,7446.86,0.0,0.0,5.0,4.85,GIANCARLO,CALLAOAPAZA,CHAVEZ,1986-02-25,2,44101109,20101036813_0137001_20171231_004.TXT,0000002595013740137001 33082482 ...,ERROR CANAL,7360,ERROR EN EL VALOR DEL CAMPO FECINIVIGENCIAPOLC...,000,
2,122189,NaN,2018-01-09,3079,Desgravamen BANBIF TC,195480,Plan Tarjetas de Crédito (01-03-16),00009004400000059526,218560883,RENOVACION,2017-12-01,2018-01-01,SOL,137.47,0.0,0.0,4.5,4.37,JULIO,ZEVALLOS,CALERO,1949-12-31,2,43250727,20101036813_0137001_20171231_004.TXT,0000040752013740137001 33082482 ...,ERROR CANAL,7360,ERROR EN EL VALOR DEL CAMPO FECINIVIGENCIAPOLC...,000,

In [13]:
df_rep_errores.info()

<class 'pandas.DataFrame'>
RangeIndex: 159067 entries, 0 to 159066
Data columns (total 31 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   NRO_LOTE            159067 non-null  str
 1   LOTES_ANTERIORES    51130 non-null   str
 2   FECHA_CARGA         159067 non-null  object
 3   CODIGO_PRODUCTO     159067 non-null  str
 4   PRODUCTO            159067 non-null  str
 5   CODIGO_PLAN         159067 non-null  str
 6   NOMBRE_DE_PLAN      159067 non-null  str
 7   CODIGO_CERTIFICADO  159067 non-null  str
 8   IDEDET              159067 non-null  str
 9   TIPO_MOVIMIENTO     159067 non-null  str
 10  FECHA_INICIO        159065 non-null  object
 11  FECHA_FIN           159065 non-null  object
 12  MONEDA              159067 non-null  str
 13  SUMA_ASEGURADA      159067 non-null  Float64
 14  TASA                159067 non-null  Float64
 15  TASA_RECARGO        159067 non-null  Float64
 16  PRIMA_BRUTA         159067 non-null  Float64
 17  PRIMA_NETA          159067 non-null  Float64
 18  NOMBRE_COMPLETO     3614 non-null    str
 19  APELLIDO_PATERNO    3627 non-null    str
 20  APELLIDO_MATERNO    3536 non-null    str
 21  FECHA_NACIMIENTO    3629 non-null    object
 22  TIPO_DOCUMENTO      3629 non-null    str
 23  NUM_DOCUMENTO       3629 non-null    str
 24  NOMBRE_DE_ARCHIVO   159067 non-null  str
 25  LINEA_TRAMA         159067 non-null  str
 26  ORIGEN_ERROR        20570 non-null   str
 27  CODIGO_ERROR        20411 non-null   str
 28  DESCRIPCION_ERROR   20570 non-null   str
 29  CODIGO_SEGURO       159067 non-null  str
 30  CODIGO_MOVIMIENTO   159067 non-null  str
dtypes: Float64(5), object(4), str(22)
memory usage: 38.4+ MB